config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "imports#index"
  resources :imports do
    get 'contacts', to: 'contacts#index'
  end

  get 'contacts', to: 'contacts#all'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  require 'credit_card_validations/string'
  belongs_to :import, inverse_of: :contacts
  belongs_to :user, inverse_of: :contacts
  scope :by_user_id, -> (user_id) {where('user_id = ?', user_id)}
  validates_presence_of :credit_card_last_4_digits, :name, :birth_date, :phone, :address, :credit_card, :franchise, :email
  validates :credit_card, presence: true, credit_card_number: true
  validate :validate_phone
  validates :email, uniqueness: { scope: [:user_id] }
  validates :email, format: { with: Devise.email_regexp }


  after_validation do
    write_attribute(:credit_card, Digest::SHA1.hexdigest(credit_card)) if credit_card.present?
  end

  def credit_card=(val)
    write_attribute(:franchise, val&.credit_card_brand_name)
    write_attribute(:credit_card_last_4_digits, val&.last(4).to_s)
    write_attribute(:credit_card, val)
  end

  def validate_phone
    regex_format1 = '\(\+\d{2}\)\s\d{3}\s\d{3}\s\d{2}\s\d{2}\s\d{2}'
    regex_format2 = '\(\+\d{2}\)\s\d{3}-\d{3}-\d{2}-\d{2}-\d{2}'
    if self.phone.present? and !self.phone.match(regex_format1) and !self.phone.match(regex_format2)
      errors.add(:phone, "invalid format")
    end
  end

end

app/models/contact_failure.rb
class ContactFailure < ApplicationRecord
  belongs_to :import
end

app/models/import.rb
require 'csv'
class Import < ApplicationRecord
  attr_accessor :csv_positions
  has_many :contacts, inverse_of: :import
  has_many :contact_failures, inverse_of: :import
  belongs_to :user, inverse_of: :imports
  enum status: [:on_hold, :processing, :failed, :finished]


  def csv_positions
    return @csv_positions if @csv_positions
    return {
      name: 0,
      phone: 1,
      birth_date: 2,
      address: 3,
      credit_card: 4,
      email: 5
    }
  end


  def process_csv(file)
    self.update_attribute(:status, :processing)
    can_have_status_finished = false
    begin
      csv_text = File.read(file)
      csv = CSV.parse(csv_text, :encoding => 'ISO-8859-1')
      csv.each_with_index do |row, index|
        contact = Contact.new({
          name: row[csv_positions[:name]],
          phone: row[csv_positions[:phone]],
          birth_date: row[csv_positions[:birth_date]],
          address: row[csv_positions[:address]],
          credit_card: row[csv_positions[:credit_card]],
          email: row[csv_positions[:email]],
          import_id: self.id,
          user_id: self.user.id
        })
        if contact.save
          can_have_status_finished = true
        else
          ContactFailure.create!({
            import_id: self.id,
            row: index,
            log: contact.errors&.messages&.to_json
          })
        end
      end
    rescue Exception => e
      Rails.logger.error("Exception found in processing csv: #{e.message}")
    ensure
      self.update_attribute(:status, can_have_status_finished ? :finished  : :failed)
    end
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :imports, inverse_of: :user
  has_many :contacts, inverse_of: :user
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  def not_found
    raise ActionController::RoutingError.new('Not Found')
  end

  protected
  def authenticate_user!
    if user_signed_in?
      super
    else
      redirect_to new_user_session_path, :notice => 'Please login'
    end
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: %i[ show edit update destroy ]
  before_action :authenticate_user!
  before_action :get_import, only: [:index]

  def all
    @contacts = Contact.by_user_id(current_user.id)
    render :index
  end

  def index
    @contacts = @import.contacts
  end

  private

  def get_import
    @import = Import.where(user_id: current_user.id).where(id: params[:import_id]).first
    not_found unless @import.nil?
  end

end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  before_action :set_import, only: %i[ show edit update destroy ]
  before_action :authenticate_user!


  # GET /imports or /imports.json
  def index
    @imports = Import.where(user_id: current_user.id)
    @contacts = Contact.by_user_id(current_user.id)
  end

  # GET /imports/1 or /imports/1.json
  def show
    @contacts = @import.contacts
    @contact_failures = @import.contact_failures
  end

  # GET /imports/new
  def new
    @import = Import.new
  end

  # POST /imports or /imports.json
  def create
    file = params[:import][:file]


    @import = Import.new({user_id: current_user.id, status: :on_hold})

    respond_to do |format|
      if @import.save
        @import.process_csv(file)
        format.html { redirect_to @import, notice: "Import #{@import.status}" }
        format.json { render :show, status: :created, location: @import }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /imports/1 or /imports/1.json
  def update
    respond_to do |format|
      if @import.update(import_params)
        format.html { redirect_to @import, notice: "Import was successfully updated." }
        format.json { render :show, status: :ok, location: @import }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @import.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /imports/1 or /imports/1.json
  def destroy
    @import.destroy
    respond_to do |format|
      format.html { redirect_to imports_url, notice: "Import was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_import
      @import = Import.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def import_params
      params.fetch(:import, {})
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
        <% contact.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<h1>Contacts</h1>

<table id="contacts">
  <thead>
    <tr>
      <th>NAME</th>
      <th>DATE OF BIRTH</th>
      <th>PHONE</th>
      <th>ADDRESS</th>
      <th>EMAIL</th>
      <th>CREDIT CARD (last 4 digits)</th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.birth_date %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.email %></td>
        <td><%= contact.credit_card_last_4_digits %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/contacts/new.html.erb
<h1>New Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path, :class => "button"  %>

app/views/contacts/show.html.erb
<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>

app/views/home/index.html.erb
<h1>Home#index</h1>

app/views/imports/_form.html.erb
<%= form_with(model: import, local: true) do |form| %>
  <%= form.file_field :file, accept: ".csv" %>
  <% if import.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(import.errors.count, "error") %> prohibited this import from being saved:</h2>

      <ul>
        <% import.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/imports/edit.html.erb
<h1>Editing Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Show', @import %> |
<%= link_to 'Back', imports_path %>

app/views/imports/index.html.erb
<h1>Imports</h1>

<table id="contacts">
  <thead>
    <tr>
      <th>ID</th>
      <th>STATUS</th>
      <th>CREATED</th>
      <th>ACTION</th>
    </tr>
  </thead>

  <tbody>
    <% @imports.each do |import| %>
      <tr>
        <td><%= import.id%></td>
        <td><%= import.status%></td>
        <td><%= import.created_at%></td>
        <td><%= link_to 'Show', import %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Import', new_import_path, :class => "button" %>

<%= render template: 'contacts/index' %>

app/views/imports/new.html.erb
<h1>New Import</h1>

<%= render 'form', import: @import %>

<%= link_to 'Back', imports_path,  :class => "button"  %>

app/views/imports/show.html.erb
<%= render template: 'contacts/index' %>



<h1>Contacts failed to create</h1>

<table id="contacts">
  <thead>
    <tr>
      <th>CSV ROW</th>
      <th>ISSUE</th>
    </tr>
  </thead>

  <tbody>
    <% @contact_failures.each do |c| %>
      <tr>
        <td><%= c.row %></td>
        <td><%= c.log %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Edit', edit_import_path(@import) %> |
<%= link_to 'Back', imports_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= link_to 'HOME', root_path, :class => "button"  %>
      <% if user_signed_in?  %>
        <%= link_to "Log out", destroy_user_session_path %>
    <% else %>
        <%= link_to "login", new_user_session_path %>
    <% end %>
    <%= yield %>
  </body>
</html>